repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: forbid-new-submodules

  - repo: https://github.com/antonbabenko/pre-commit-terraform.git
    rev: v1.69.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_docs